// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

//go:generate easyjson
import contract "go.arwos.org/atlas/app/types"

//easyjson:json
type jsonrpcDHCPDraftGetModelRequest struct{}

//easyjson:json
type jsonrpcDHCPDraftGetModelResponse struct {
	Configuration contract.DHCPConfigurationResponse `json:"configuration"`
}

//easyjson:json
type jsonrpcDHCPActiveGetModelRequest struct{}

//easyjson:json
type jsonrpcDHCPActiveGetModelResponse struct {
	Configuration contract.DHCPConfigurationResponse `json:"configuration"`
}

//easyjson:json
type jsonrpcDHCPSubnetUpsertModelRequest struct {
	Subnet contract.DHCPSubnetUpsertRequest `json:"subnet"`
}

//easyjson:json
type jsonrpcDHCPSubnetUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPSubnetDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDHCPSubnetDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPReservationUpsertModelRequest struct {
	Reservation contract.DHCPReservationUpsertRequest `json:"reservation"`
}

//easyjson:json
type jsonrpcDHCPReservationUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPReservationDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDHCPReservationDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPBlockUpsertModelRequest struct {
	Block contract.DHCPBlockUpsertRequest `json:"block"`
}

//easyjson:json
type jsonrpcDHCPBlockUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPBlockDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDHCPBlockDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPApplyModelRequest struct{}

//easyjson:json
type jsonrpcDHCPApplyModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPLeaseRevokeModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDHCPLeaseRevokeModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPLeaseListModelRequest struct{}

//easyjson:json
type jsonrpcDHCPLeaseListModelResponse struct {
	Leases []contract.DHCPLeaseResponse `json:"leases,omitempty"`
}

//easyjson:json
type jsonrpcDNSDraftGetDNSModelRequest struct{}

//easyjson:json
type jsonrpcDNSDraftGetDNSModelResponse struct {
	Configuration contract.DNSConfigurationResponse `json:"configuration"`
}

//easyjson:json
type jsonrpcDNSActiveGetDNSModelRequest struct{}

//easyjson:json
type jsonrpcDNSActiveGetDNSModelResponse struct {
	Configuration contract.DNSConfigurationResponse `json:"configuration"`
}

//easyjson:json
type jsonrpcDNSZoneUpsertModelRequest struct {
	Zone contract.DNSZoneUpsertRequest `json:"zone"`
}

//easyjson:json
type jsonrpcDNSZoneUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDNSZoneDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDNSZoneDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDNSRecordUpsertModelRequest struct {
	Record contract.DNSRecordUpsertRequest `json:"record"`
}

//easyjson:json
type jsonrpcDNSRecordUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDNSRecordDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDNSRecordDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDNSForwarderUpsertModelRequest struct {
	Forwarder contract.DNSForwarderUpsertRequest `json:"forwarder"`
}

//easyjson:json
type jsonrpcDNSForwarderUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDNSForwarderDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDNSForwarderDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDNSDNSBlockUpsertModelRequest struct {
	Block contract.DNSBlockUpsertRequest `json:"block"`
}

//easyjson:json
type jsonrpcDNSDNSBlockUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDNSDNSBlockDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDNSDNSBlockDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDNSApplyDNSModelRequest struct{}

//easyjson:json
type jsonrpcDNSApplyDNSModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}
