// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

import (
	context "context"
	fmt "fmt"

	contract "go.arwos.org/atlas/app/types"

	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"

	stdjson "encoding/json"

	web "go.osspkg.com/goppy/v3/plugins/web"
)

type JSONRPCDNSTransport struct {
	handle contract.DNS
	tags   []string
}

func NewJSONRPCDNSTransport(handle contract.DNS, tags []string) *JSONRPCDNSTransport {
	return &JSONRPCDNSTransport{
		handle: handle,
		tags:   tags,
	}
}

func (v *JSONRPCDNSTransport) RouteTags() []string {
	return v.tags
}

func (v *JSONRPCDNSTransport) JSONRPCApiHandlers() map[string]jsonrpc.THandleFunc {
	return map[string]jsonrpc.THandleFunc{
		"dns.draftgetdns":     v.CallDraftGetDNS,
		"dns.activegetdns":    v.CallActiveGetDNS,
		"dns.zoneupsert":      v.CallZoneUpsert,
		"dns.zonedelete":      v.CallZoneDelete,
		"dns.recordupsert":    v.CallRecordUpsert,
		"dns.recorddelete":    v.CallRecordDelete,
		"dns.forwarderupsert": v.CallForwarderUpsert,
		"dns.forwarderdelete": v.CallForwarderDelete,
		"dns.dnsblockupsert":  v.CallDNSBlockUpsert,
		"dns.dnsblockdelete":  v.CallDNSBlockDelete,
		"dns.applydns":        v.CallApplyDNS,
	}
}

func (v *JSONRPCDNSTransport) CallDraftGetDNS(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSDraftGetDNSModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSDraftGetDNSModelResponse
	res.Configuration, err = v.handle.DraftGetDNS(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallActiveGetDNS(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSActiveGetDNSModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSActiveGetDNSModelResponse
	res.Configuration, err = v.handle.ActiveGetDNS(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallZoneUpsert(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSZoneUpsertModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSZoneUpsertModelResponse
	res.Operation, err = v.handle.ZoneUpsert(ctx, req.Zone)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallZoneDelete(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSZoneDeleteModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSZoneDeleteModelResponse
	res.Operation, err = v.handle.ZoneDelete(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallRecordUpsert(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSRecordUpsertModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSRecordUpsertModelResponse
	res.Operation, err = v.handle.RecordUpsert(ctx, req.Record)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallRecordDelete(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSRecordDeleteModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSRecordDeleteModelResponse
	res.Operation, err = v.handle.RecordDelete(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallForwarderUpsert(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSForwarderUpsertModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSForwarderUpsertModelResponse
	res.Operation, err = v.handle.ForwarderUpsert(ctx, req.Forwarder)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallForwarderDelete(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSForwarderDeleteModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSForwarderDeleteModelResponse
	res.Operation, err = v.handle.ForwarderDelete(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallDNSBlockUpsert(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSDNSBlockUpsertModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSDNSBlockUpsertModelResponse
	res.Operation, err = v.handle.DNSBlockUpsert(ctx, req.Block)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallDNSBlockDelete(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSDNSBlockDeleteModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSDNSBlockDeleteModelResponse
	res.Operation, err = v.handle.DNSBlockDelete(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDNSTransport) CallApplyDNS(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDNSApplyDNSModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDNSApplyDNSModelResponse
	res.Operation, err = v.handle.ApplyDNS(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
