// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package transport

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"

	types "go.arwos.org/atlas/app/types"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport(in *jlexer.Lexer, out *jsonrpcDHCPSubnetUpsertModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in, &out.Operation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport(out *jwriter.Writer, in jsonrpcDHCPSubnetUpsertModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out, in.Operation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPSubnetUpsertModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPSubnetUpsertModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPSubnetUpsertModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPSubnetUpsertModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in *jlexer.Lexer, out *types.OperationResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out *jwriter.Writer, in types.OperationResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Success))
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport1(in *jlexer.Lexer, out *jsonrpcDHCPSubnetUpsertModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "subnet":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes1(in, &out.Subnet)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport1(out *jwriter.Writer, in jsonrpcDHCPSubnetUpsertModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subnet\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes1(out, in.Subnet)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPSubnetUpsertModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPSubnetUpsertModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPSubnetUpsertModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPSubnetUpsertModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport1(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes1(in *jlexer.Lexer, out *types.DHCPSubnetUpsertRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "interface":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Interface = string(in.String())
			}
		case "cidr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CIDR = string(in.String())
			}
		case "lease_seconds":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LeaseSeconds = int64(in.Int64())
			}
		case "router":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Router = string(in.String())
			}
		case "dns_servers":
			if in.IsNull() {
				in.Skip()
				out.DNSServers = nil
			} else {
				in.Delim('[')
				if out.DNSServers == nil {
					if !in.IsDelim(']') {
						out.DNSServers = make([]string, 0, 4)
					} else {
						out.DNSServers = []string{}
					}
				} else {
					out.DNSServers = (out.DNSServers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.DNSServers = append(out.DNSServers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "domain_search":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DomainSearch = string(in.String())
			}
		case "ntp_servers":
			if in.IsNull() {
				in.Skip()
				out.NTPServers = nil
			} else {
				in.Delim('[')
				if out.NTPServers == nil {
					if !in.IsDelim(']') {
						out.NTPServers = make([]string, 0, 4)
					} else {
						out.NTPServers = []string{}
					}
				} else {
					out.NTPServers = (out.NTPServers)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.NTPServers = append(out.NTPServers, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "mtu":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MTU = int(in.Int())
			}
		case "classless_routes":
			if in.IsNull() {
				in.Skip()
				out.ClasslessRoutes = nil
			} else {
				in.Delim('[')
				if out.ClasslessRoutes == nil {
					if !in.IsDelim(']') {
						out.ClasslessRoutes = make([]string, 0, 4)
					} else {
						out.ClasslessRoutes = []string{}
					}
				} else {
					out.ClasslessRoutes = (out.ClasslessRoutes)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.ClasslessRoutes = append(out.ClasslessRoutes, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes1(out *jwriter.Writer, in types.DHCPSubnetUpsertRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"interface\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Interface))
	}
	{
		const prefix string = ",\"cidr\":"
		out.RawString(prefix)
		out.String(string(in.CIDR))
	}
	{
		const prefix string = ",\"lease_seconds\":"
		out.RawString(prefix)
		out.Int64(int64(in.LeaseSeconds))
	}
	if in.Router != "" {
		const prefix string = ",\"router\":"
		out.RawString(prefix)
		out.String(string(in.Router))
	}
	if len(in.DNSServers) != 0 {
		const prefix string = ",\"dns_servers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v4, v5 := range in.DNSServers {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.String(string(v5))
			}
			out.RawByte(']')
		}
	}
	if in.DomainSearch != "" {
		const prefix string = ",\"domain_search\":"
		out.RawString(prefix)
		out.String(string(in.DomainSearch))
	}
	if len(in.NTPServers) != 0 {
		const prefix string = ",\"ntp_servers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.NTPServers {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	if in.MTU != 0 {
		const prefix string = ",\"mtu\":"
		out.RawString(prefix)
		out.Int(int(in.MTU))
	}
	if len(in.ClasslessRoutes) != 0 {
		const prefix string = ",\"classless_routes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.ClasslessRoutes {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport2(in *jlexer.Lexer, out *jsonrpcDHCPSubnetDeleteModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in, &out.Operation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport2(out *jwriter.Writer, in jsonrpcDHCPSubnetDeleteModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out, in.Operation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPSubnetDeleteModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPSubnetDeleteModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPSubnetDeleteModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPSubnetDeleteModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport2(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport3(in *jlexer.Lexer, out *jsonrpcDHCPSubnetDeleteModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport3(out *jwriter.Writer, in jsonrpcDHCPSubnetDeleteModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPSubnetDeleteModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPSubnetDeleteModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPSubnetDeleteModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPSubnetDeleteModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport3(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport4(in *jlexer.Lexer, out *jsonrpcDHCPReservationUpsertModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in, &out.Operation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport4(out *jwriter.Writer, in jsonrpcDHCPReservationUpsertModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out, in.Operation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPReservationUpsertModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPReservationUpsertModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPReservationUpsertModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPReservationUpsertModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport4(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport5(in *jlexer.Lexer, out *jsonrpcDHCPReservationUpsertModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "reservation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes2(in, &out.Reservation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport5(out *jwriter.Writer, in jsonrpcDHCPReservationUpsertModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"reservation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes2(out, in.Reservation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPReservationUpsertModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPReservationUpsertModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPReservationUpsertModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPReservationUpsertModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport5(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes2(in *jlexer.Lexer, out *types.DHCPReservationUpsertRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "subnet_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubnetID = int64(in.Int64())
			}
		case "mac":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MAC = string(in.String())
			}
		case "ip":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IP = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes2(out *jwriter.Writer, in types.DHCPReservationUpsertRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"subnet_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.SubnetID))
	}
	{
		const prefix string = ",\"mac\":"
		out.RawString(prefix)
		out.String(string(in.MAC))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		out.String(string(in.IP))
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport6(in *jlexer.Lexer, out *jsonrpcDHCPReservationDeleteModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in, &out.Operation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport6(out *jwriter.Writer, in jsonrpcDHCPReservationDeleteModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out, in.Operation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPReservationDeleteModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPReservationDeleteModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPReservationDeleteModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPReservationDeleteModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport6(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport7(in *jlexer.Lexer, out *jsonrpcDHCPReservationDeleteModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport7(out *jwriter.Writer, in jsonrpcDHCPReservationDeleteModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPReservationDeleteModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPReservationDeleteModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPReservationDeleteModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPReservationDeleteModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport7(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport8(in *jlexer.Lexer, out *jsonrpcDHCPLeaseRevokeModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in, &out.Operation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport8(out *jwriter.Writer, in jsonrpcDHCPLeaseRevokeModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out, in.Operation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPLeaseRevokeModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPLeaseRevokeModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPLeaseRevokeModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPLeaseRevokeModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport8(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport9(in *jlexer.Lexer, out *jsonrpcDHCPLeaseRevokeModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport9(out *jwriter.Writer, in jsonrpcDHCPLeaseRevokeModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPLeaseRevokeModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPLeaseRevokeModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPLeaseRevokeModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPLeaseRevokeModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport9(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport10(in *jlexer.Lexer, out *jsonrpcDHCPLeaseListModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "leases":
			if in.IsNull() {
				in.Skip()
				out.Leases = nil
			} else {
				in.Delim('[')
				if out.Leases == nil {
					if !in.IsDelim(']') {
						out.Leases = make([]types.DHCPLeaseResponse, 0, 0)
					} else {
						out.Leases = []types.DHCPLeaseResponse{}
					}
				} else {
					out.Leases = (out.Leases)[:0]
				}
				for !in.IsDelim(']') {
					var v10 types.DHCPLeaseResponse
					easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes3(in, &v10)
					out.Leases = append(out.Leases, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport10(out *jwriter.Writer, in jsonrpcDHCPLeaseListModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Leases) != 0 {
		const prefix string = ",\"leases\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v11, v12 := range in.Leases {
				if v11 > 0 {
					out.RawByte(',')
				}
				easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes3(out, v12)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPLeaseListModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPLeaseListModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPLeaseListModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPLeaseListModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport10(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes3(in *jlexer.Lexer, out *types.DHCPLeaseResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "subnet_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubnetID = int64(in.Int64())
			}
		case "mac":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MAC = string(in.String())
			}
		case "ip":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IP = string(in.String())
			}
		case "expires_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ExpiresAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes3(out *jwriter.Writer, in types.DHCPLeaseResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"subnet_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SubnetID))
	}
	{
		const prefix string = ",\"mac\":"
		out.RawString(prefix)
		out.String(string(in.MAC))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		out.String(string(in.IP))
	}
	{
		const prefix string = ",\"expires_at\":"
		out.RawString(prefix)
		out.Raw((in.ExpiresAt).MarshalJSON())
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport11(in *jlexer.Lexer, out *jsonrpcDHCPLeaseListModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport11(out *jwriter.Writer, in jsonrpcDHCPLeaseListModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPLeaseListModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPLeaseListModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPLeaseListModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPLeaseListModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport11(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport12(in *jlexer.Lexer, out *jsonrpcDHCPDraftGetModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "configuration":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes4(in, &out.Configuration)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport12(out *jwriter.Writer, in jsonrpcDHCPDraftGetModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"configuration\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes4(out, in.Configuration)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPDraftGetModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPDraftGetModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPDraftGetModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPDraftGetModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport12(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes4(in *jlexer.Lexer, out *types.DHCPConfigurationResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "subnets":
			if in.IsNull() {
				in.Skip()
				out.Subnets = nil
			} else {
				in.Delim('[')
				if out.Subnets == nil {
					if !in.IsDelim(']') {
						out.Subnets = make([]types.DHCPSubnetResponse, 0, 0)
					} else {
						out.Subnets = []types.DHCPSubnetResponse{}
					}
				} else {
					out.Subnets = (out.Subnets)[:0]
				}
				for !in.IsDelim(']') {
					var v13 types.DHCPSubnetResponse
					easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes5(in, &v13)
					out.Subnets = append(out.Subnets, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "reservations":
			if in.IsNull() {
				in.Skip()
				out.Reservations = nil
			} else {
				in.Delim('[')
				if out.Reservations == nil {
					if !in.IsDelim(']') {
						out.Reservations = make([]types.DHCPReservationResponse, 0, 1)
					} else {
						out.Reservations = []types.DHCPReservationResponse{}
					}
				} else {
					out.Reservations = (out.Reservations)[:0]
				}
				for !in.IsDelim(']') {
					var v14 types.DHCPReservationResponse
					easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes6(in, &v14)
					out.Reservations = append(out.Reservations, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "blocks":
			if in.IsNull() {
				in.Skip()
				out.Blocks = nil
			} else {
				in.Delim('[')
				if out.Blocks == nil {
					if !in.IsDelim(']') {
						out.Blocks = make([]types.DHCPBlockResponse, 0, 2)
					} else {
						out.Blocks = []types.DHCPBlockResponse{}
					}
				} else {
					out.Blocks = (out.Blocks)[:0]
				}
				for !in.IsDelim(']') {
					var v15 types.DHCPBlockResponse
					easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes7(in, &v15)
					out.Blocks = append(out.Blocks, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes4(out *jwriter.Writer, in types.DHCPConfigurationResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subnets\":"
		out.RawString(prefix[1:])
		if in.Subnets == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.Subnets {
				if v16 > 0 {
					out.RawByte(',')
				}
				easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes5(out, v17)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"reservations\":"
		out.RawString(prefix)
		if in.Reservations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.Reservations {
				if v18 > 0 {
					out.RawByte(',')
				}
				easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes6(out, v19)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"blocks\":"
		out.RawString(prefix)
		if in.Blocks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Blocks {
				if v20 > 0 {
					out.RawByte(',')
				}
				easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes7(out, v21)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes7(in *jlexer.Lexer, out *types.DHCPBlockResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "mac":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MAC = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes7(out *jwriter.Writer, in types.DHCPBlockResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"mac\":"
		out.RawString(prefix)
		out.String(string(in.MAC))
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes6(in *jlexer.Lexer, out *types.DHCPReservationResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "subnet_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubnetID = int64(in.Int64())
			}
		case "mac":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MAC = string(in.String())
			}
		case "ip":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IP = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes6(out *jwriter.Writer, in types.DHCPReservationResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"subnet_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SubnetID))
	}
	{
		const prefix string = ",\"mac\":"
		out.RawString(prefix)
		out.String(string(in.MAC))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		out.String(string(in.IP))
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes5(in *jlexer.Lexer, out *types.DHCPSubnetResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "interface":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Interface = string(in.String())
			}
		case "cidr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CIDR = string(in.String())
			}
		case "lease_seconds":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LeaseSeconds = int64(in.Int64())
			}
		case "router":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Router = string(in.String())
			}
		case "dns_servers":
			if in.IsNull() {
				in.Skip()
				out.DNSServers = nil
			} else {
				in.Delim('[')
				if out.DNSServers == nil {
					if !in.IsDelim(']') {
						out.DNSServers = make([]string, 0, 4)
					} else {
						out.DNSServers = []string{}
					}
				} else {
					out.DNSServers = (out.DNSServers)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.DNSServers = append(out.DNSServers, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "domain_search":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DomainSearch = string(in.String())
			}
		case "ntp_servers":
			if in.IsNull() {
				in.Skip()
				out.NTPServers = nil
			} else {
				in.Delim('[')
				if out.NTPServers == nil {
					if !in.IsDelim(']') {
						out.NTPServers = make([]string, 0, 4)
					} else {
						out.NTPServers = []string{}
					}
				} else {
					out.NTPServers = (out.NTPServers)[:0]
				}
				for !in.IsDelim(']') {
					var v23 string
					if in.IsNull() {
						in.Skip()
					} else {
						v23 = string(in.String())
					}
					out.NTPServers = append(out.NTPServers, v23)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "mtu":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MTU = int(in.Int())
			}
		case "classless_routes":
			if in.IsNull() {
				in.Skip()
				out.ClasslessRoutes = nil
			} else {
				in.Delim('[')
				if out.ClasslessRoutes == nil {
					if !in.IsDelim(']') {
						out.ClasslessRoutes = make([]string, 0, 4)
					} else {
						out.ClasslessRoutes = []string{}
					}
				} else {
					out.ClasslessRoutes = (out.ClasslessRoutes)[:0]
				}
				for !in.IsDelim(']') {
					var v24 string
					if in.IsNull() {
						in.Skip()
					} else {
						v24 = string(in.String())
					}
					out.ClasslessRoutes = append(out.ClasslessRoutes, v24)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes5(out *jwriter.Writer, in types.DHCPSubnetResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"interface\":"
		out.RawString(prefix)
		out.String(string(in.Interface))
	}
	{
		const prefix string = ",\"cidr\":"
		out.RawString(prefix)
		out.String(string(in.CIDR))
	}
	{
		const prefix string = ",\"lease_seconds\":"
		out.RawString(prefix)
		out.Int64(int64(in.LeaseSeconds))
	}
	if in.Router != "" {
		const prefix string = ",\"router\":"
		out.RawString(prefix)
		out.String(string(in.Router))
	}
	if len(in.DNSServers) != 0 {
		const prefix string = ",\"dns_servers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v25, v26 := range in.DNSServers {
				if v25 > 0 {
					out.RawByte(',')
				}
				out.String(string(v26))
			}
			out.RawByte(']')
		}
	}
	if in.DomainSearch != "" {
		const prefix string = ",\"domain_search\":"
		out.RawString(prefix)
		out.String(string(in.DomainSearch))
	}
	if len(in.NTPServers) != 0 {
		const prefix string = ",\"ntp_servers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v27, v28 := range in.NTPServers {
				if v27 > 0 {
					out.RawByte(',')
				}
				out.String(string(v28))
			}
			out.RawByte(']')
		}
	}
	if in.MTU != 0 {
		const prefix string = ",\"mtu\":"
		out.RawString(prefix)
		out.Int(int(in.MTU))
	}
	if len(in.ClasslessRoutes) != 0 {
		const prefix string = ",\"classless_routes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v29, v30 := range in.ClasslessRoutes {
				if v29 > 0 {
					out.RawByte(',')
				}
				out.String(string(v30))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport13(in *jlexer.Lexer, out *jsonrpcDHCPDraftGetModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport13(out *jwriter.Writer, in jsonrpcDHCPDraftGetModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPDraftGetModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPDraftGetModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPDraftGetModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPDraftGetModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport13(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport14(in *jlexer.Lexer, out *jsonrpcDHCPBlockUpsertModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in, &out.Operation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport14(out *jwriter.Writer, in jsonrpcDHCPBlockUpsertModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out, in.Operation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPBlockUpsertModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPBlockUpsertModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPBlockUpsertModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPBlockUpsertModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport14(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport15(in *jlexer.Lexer, out *jsonrpcDHCPBlockUpsertModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "block":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes8(in, &out.Block)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport15(out *jwriter.Writer, in jsonrpcDHCPBlockUpsertModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes8(out, in.Block)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPBlockUpsertModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPBlockUpsertModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPBlockUpsertModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPBlockUpsertModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport15(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes8(in *jlexer.Lexer, out *types.DHCPBlockUpsertRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "mac":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MAC = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes8(out *jwriter.Writer, in types.DHCPBlockUpsertRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"mac\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.MAC))
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport16(in *jlexer.Lexer, out *jsonrpcDHCPBlockDeleteModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in, &out.Operation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport16(out *jwriter.Writer, in jsonrpcDHCPBlockDeleteModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out, in.Operation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPBlockDeleteModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPBlockDeleteModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPBlockDeleteModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPBlockDeleteModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport16(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport17(in *jlexer.Lexer, out *jsonrpcDHCPBlockDeleteModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport17(out *jwriter.Writer, in jsonrpcDHCPBlockDeleteModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPBlockDeleteModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPBlockDeleteModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPBlockDeleteModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPBlockDeleteModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport17(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport18(in *jlexer.Lexer, out *jsonrpcDHCPApplyModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes(in, &out.Operation)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport18(out *jwriter.Writer, in jsonrpcDHCPApplyModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes(out, in.Operation)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPApplyModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPApplyModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPApplyModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPApplyModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport18(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport19(in *jlexer.Lexer, out *jsonrpcDHCPApplyModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport19(out *jwriter.Writer, in jsonrpcDHCPApplyModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPApplyModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport19(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPApplyModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport19(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPApplyModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport19(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPApplyModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport19(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport20(in *jlexer.Lexer, out *jsonrpcDHCPActiveGetModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "configuration":
			easyjson3ef10231DecodeGoArwosOrgAtlasAppTypes4(in, &out.Configuration)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport20(out *jwriter.Writer, in jsonrpcDHCPActiveGetModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"configuration\":"
		out.RawString(prefix[1:])
		easyjson3ef10231EncodeGoArwosOrgAtlasAppTypes4(out, in.Configuration)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPActiveGetModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport20(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPActiveGetModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport20(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPActiveGetModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport20(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPActiveGetModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport20(l, v)
}
func easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport21(in *jlexer.Lexer, out *jsonrpcDHCPActiveGetModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport21(out *jwriter.Writer, in jsonrpcDHCPActiveGetModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcDHCPActiveGetModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport21(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcDHCPActiveGetModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoArwosOrgAtlasAppTransport21(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcDHCPActiveGetModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport21(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcDHCPActiveGetModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoArwosOrgAtlasAppTransport21(l, v)
}
