// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

import (
	context "context"
	fmt "fmt"

	contract "go.arwos.org/atlas/app/types"

	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"

	stdjson "encoding/json"

	web "go.osspkg.com/goppy/v3/plugins/web"
)

type JSONRPCDHCPTransport struct {
	handle contract.DHCP
	tags   []string
}

func NewJSONRPCDHCPTransport(handle contract.DHCP, tags []string) *JSONRPCDHCPTransport {
	return &JSONRPCDHCPTransport{
		handle: handle,
		tags:   tags,
	}
}

func (v *JSONRPCDHCPTransport) RouteTags() []string {
	return v.tags
}

func (v *JSONRPCDHCPTransport) JSONRPCApiHandlers() map[string]jsonrpc.THandleFunc {
	return map[string]jsonrpc.THandleFunc{
		"dhcp.draftget":          v.CallDraftGet,
		"dhcp.activeget":         v.CallActiveGet,
		"dhcp.subnetupsert":      v.CallSubnetUpsert,
		"dhcp.subnetdelete":      v.CallSubnetDelete,
		"dhcp.reservationupsert": v.CallReservationUpsert,
		"dhcp.reservationdelete": v.CallReservationDelete,
		"dhcp.blockupsert":       v.CallBlockUpsert,
		"dhcp.blockdelete":       v.CallBlockDelete,
		"dhcp.apply":             v.CallApply,
		"dhcp.leaserevoke":       v.CallLeaseRevoke,
		"dhcp.leaselist":         v.CallLeaseList,
	}
}

func (v *JSONRPCDHCPTransport) CallDraftGet(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPDraftGetModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPDraftGetModelResponse
	res.Configuration, err = v.handle.DraftGet(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallActiveGet(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPActiveGetModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPActiveGetModelResponse
	res.Configuration, err = v.handle.ActiveGet(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallSubnetUpsert(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPSubnetUpsertModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPSubnetUpsertModelResponse
	res.Operation, err = v.handle.SubnetUpsert(ctx, req.Subnet)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallSubnetDelete(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPSubnetDeleteModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPSubnetDeleteModelResponse
	res.Operation, err = v.handle.SubnetDelete(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallReservationUpsert(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPReservationUpsertModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPReservationUpsertModelResponse
	res.Operation, err = v.handle.ReservationUpsert(ctx, req.Reservation)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallReservationDelete(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPReservationDeleteModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPReservationDeleteModelResponse
	res.Operation, err = v.handle.ReservationDelete(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallBlockUpsert(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPBlockUpsertModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPBlockUpsertModelResponse
	res.Operation, err = v.handle.BlockUpsert(ctx, req.Block)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallBlockDelete(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPBlockDeleteModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPBlockDeleteModelResponse
	res.Operation, err = v.handle.BlockDelete(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallApply(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPApplyModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPApplyModelResponse
	res.Operation, err = v.handle.Apply(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallLeaseRevoke(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPLeaseRevokeModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPLeaseRevokeModelResponse
	res.Operation, err = v.handle.LeaseRevoke(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCDHCPTransport) CallLeaseList(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcDHCPLeaseListModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcDHCPLeaseListModelResponse
	res.Leases, err = v.handle.LeaseList(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
