// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

//go:generate easyjson
import contract "go.arwos.org/atlas/app/types"

//easyjson:json
type jsonrpcDHCPDraftGetModelRequest struct{}

//easyjson:json
type jsonrpcDHCPDraftGetModelResponse struct {
	Configuration contract.DHCPConfigurationResponse `json:"configuration"`
}

//easyjson:json
type jsonrpcDHCPActiveGetModelRequest struct{}

//easyjson:json
type jsonrpcDHCPActiveGetModelResponse struct {
	Configuration contract.DHCPConfigurationResponse `json:"configuration"`
}

//easyjson:json
type jsonrpcDHCPSubnetUpsertModelRequest struct {
	Subnet contract.DHCPSubnetUpsertRequest `json:"subnet"`
}

//easyjson:json
type jsonrpcDHCPSubnetUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPSubnetDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDHCPSubnetDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPReservationUpsertModelRequest struct {
	Reservation contract.DHCPReservationUpsertRequest `json:"reservation"`
}

//easyjson:json
type jsonrpcDHCPReservationUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPReservationDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDHCPReservationDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPBlockUpsertModelRequest struct {
	Block contract.DHCPBlockUpsertRequest `json:"block"`
}

//easyjson:json
type jsonrpcDHCPBlockUpsertModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPBlockDeleteModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDHCPBlockDeleteModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPApplyModelRequest struct{}

//easyjson:json
type jsonrpcDHCPApplyModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPLeaseRevokeModelRequest struct {
	Id int64 `json:"id"`
}

//easyjson:json
type jsonrpcDHCPLeaseRevokeModelResponse struct {
	Operation contract.OperationResponse `json:"operation"`
}

//easyjson:json
type jsonrpcDHCPLeaseListModelRequest struct{}

//easyjson:json
type jsonrpcDHCPLeaseListModelResponse struct {
	Leases []contract.DHCPLeaseResponse `json:"leases,omitempty"`
}
