/*
 *  Copyright (c) 2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Package contract defines the generated DHCP transport contract.
package contract

import (
	"context"
	"time"
)

// DHCP is the JSON-RPC contract generated by goppy tb.
type DHCP interface {
	DraftGet(ctx context.Context) (configuration DHCPConfigurationResponse, err error)
	ActiveGet(ctx context.Context) (configuration DHCPConfigurationResponse, err error)
	SubnetUpsert(ctx context.Context, subnet DHCPSubnetUpsertRequest) (operation OperationResponse, err error)
	SubnetDelete(ctx context.Context, id int64) (operation OperationResponse, err error)
	ReservationUpsert(ctx context.Context, reservation DHCPReservationUpsertRequest) (operation OperationResponse, err error)
	ReservationDelete(ctx context.Context, id int64) (operation OperationResponse, err error)
	BlockUpsert(ctx context.Context, block DHCPBlockUpsertRequest) (operation OperationResponse, err error)
	BlockDelete(ctx context.Context, id int64) (operation OperationResponse, err error)
	Apply(ctx context.Context) (operation OperationResponse, err error)
	LeaseRevoke(ctx context.Context, id int64) (operation OperationResponse, err error)
	LeaseList(ctx context.Context) (leases []DHCPLeaseResponse, err error)
}

// DHCPSubnetUpsertRequest creates or updates a DHCP subnet.
type DHCPSubnetUpsertRequest struct {
	ID              int64    `json:"id,omitempty"`
	Interface       string   `json:"interface"`
	CIDR            string   `json:"cidr"`
	LeaseSeconds    int64    `json:"lease_seconds"`
	Router          string   `json:"router,omitempty"`
	DNSServers      []string `json:"dns_servers,omitempty"`
	DomainSearch    string   `json:"domain_search,omitempty"`
	NTPServers      []string `json:"ntp_servers,omitempty"`
	MTU             int      `json:"mtu,omitempty"`
	ClasslessRoutes []string `json:"classless_routes,omitempty"`
}

// DHCPReservationUpsertRequest creates or updates a DHCP reservation.
type DHCPReservationUpsertRequest struct {
	ID       int64  `json:"id,omitempty"`
	SubnetID int64  `json:"subnet_id"`
	MAC      string `json:"mac"`
	IP       string `json:"ip"`
}

// DHCPBlockUpsertRequest creates or updates a DHCP block.
type DHCPBlockUpsertRequest struct {
	ID  int64  `json:"id,omitempty"`
	MAC string `json:"mac"`
}

// OperationResponse reports whether a requested operation succeeded.
type OperationResponse struct {
	Success bool `json:"success"`
}

// DHCPSubnetResponse represents a DHCP subnet over JSON-RPC.
type DHCPSubnetResponse struct {
	ID              int64    `json:"id"`
	Interface       string   `json:"interface"`
	CIDR            string   `json:"cidr"`
	LeaseSeconds    int64    `json:"lease_seconds"`
	Router          string   `json:"router,omitempty"`
	DNSServers      []string `json:"dns_servers,omitempty"`
	DomainSearch    string   `json:"domain_search,omitempty"`
	NTPServers      []string `json:"ntp_servers,omitempty"`
	MTU             int      `json:"mtu,omitempty"`
	ClasslessRoutes []string `json:"classless_routes,omitempty"`
}

// DHCPReservationResponse represents a DHCP reservation over JSON-RPC.
type DHCPReservationResponse struct {
	ID       int64  `json:"id"`
	SubnetID int64  `json:"subnet_id"`
	MAC      string `json:"mac"`
	IP       string `json:"ip"`
}

// DHCPBlockResponse represents a DHCP block over JSON-RPC.
type DHCPBlockResponse struct {
	ID  int64  `json:"id"`
	MAC string `json:"mac"`
}

// DHCPLeaseResponse represents a DHCP lease over JSON-RPC.
type DHCPLeaseResponse struct {
	ID        int64     `json:"id"`
	SubnetID  int64     `json:"subnet_id"`
	MAC       string    `json:"mac"`
	IP        string    `json:"ip"`
	ExpiresAt time.Time `json:"expires_at"`
}

// DHCPConfigurationResponse represents a complete DHCP configuration over JSON-RPC.
type DHCPConfigurationResponse struct {
	Subnets      []DHCPSubnetResponse      `json:"subnets"`
	Reservations []DHCPReservationResponse `json:"reservations"`
	Blocks       []DHCPBlockResponse       `json:"blocks"`
}
